wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693336923.423555
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 31
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 31
      - 49
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.9.16
      5: 0.15.8
      6: 4.31.0
      8:
      - 3
      - 5
